"""reading sessions

Revision ID: 136445b6d745
Revises: 3f02446b4fd5
Create Date: 2026-08-06 21:10:40.000477

"""
from alembic import op
import sqlalchemy as sa


revision = '136445b6d745'
down_revision = '3f02446b4fd5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reading_sessions_article_id'), 'reading_sessions', ['article_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reading_sessions_article_id'), table_name='reading_sessions')
    op.drop_table('reading_sessions')
    # ### end Alembic commands ###
